[programs.devnet]
rizzlr_escrow = "7Qiy37JApZuYj24dPS5bZd7QkE9QVRJbMQozoY6u2zYJ"

[programs.localnet]
rizzlr_escrow = "7Qiy37JApZuYj24dPS5bZd7QkE9QVRJbMQozoY6u2zYJ"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "echo \"anchor test — install Anchor CLI to run\""
