[programs.devnet]
rizzlr_escrow = "8VXrjswABWW7y7MNsXfG7EcP39P18E75KxcxmX7yYk1W"

[programs.localnet]
rizzlr_escrow = "8VXrjswABWW7y7MNsXfG7EcP39P18E75KxcxmX7yYk1W"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "echo \"anchor test — install Anchor CLI to run\""
